export const USER_MESSAGES = {
    EMAIL_EXISTED: 'Email đã tồn tại',
    PHONE_EXISTED: 'Số điện thoại đã tồn tại',
    USER_NOT_ACTIVE: 'Tài khoản chưa được kích hoạt',
    USER_NOT_FOUND: 'Không tìm thấy người dùng',
    USER_DISABLED: 'Tài khoản đã vô hiệu hóa',
    USER_NOT_DISABLED: 'Tài khoản chưa vô hiệu hóa',
    DISABLE_SUCCESS: 'Vô hiệu hóa thành công',
    ENABLE_SUCCESS: 'Đã kích hoạt lại tài khoản',
    CANNOT_DISABLE_ADMIN: 'Không thể vô hiệu hóa tài khoản ADMIN',
    PASSWORD_NOT_SET: 'Tài khoản chưa thiết lập mật khẩu',
    USER_BANNED: 'Tài khoản đã bị khóa',
    PASSWORD_ALREADY_SET: 'Tài khoản đã có mật khẩu',
    USER_ALREADY_ACTIVE: 'Tài khoản đã được kích hoạt',
    ACTIVE_SUCCESS: 'Kích hoạt tài khoản thành công',
    REGISTER_CHECK_EMAIL:
        'Vui lòng kiểm tra hộp thư emai để kích hoạt tài khoản',
    BIO_NOT_EXISTED: 'Người dùng không có tiểu sử',
    CODE_EXPIRED: 'Mã đã hết hạn',
    CREATE_PASSWORD_SUCCESS: 'Tạo mật khẩu thành công',
    INVALID_CODE: 'Mã không hợp lệ',
    ROLE_NOT_CHANGED: 'Vai trò không thay đổi',
    MISSING_PERMISSION: 'Bạn không có quyền thực hiện thao tác này',
    INVALID_PASSWORD: 'Mật khẩu không hợp lệ',
    CHANGE_PASSWORD_SUCCESS: 'Đổi mật khẩu thành công',
    EMAIL_NOT_FOUND: 'Không tìm thấy email',
    RESET_PASSWORD_SUCCESS: 'Đặt lại mật khẩu thành công',
    PLEASE_WAIT_COOLDOWN: (waitTime: number) => `Vui lòng chờ ${waitTime} giây`,
    FILE_UPLOAD_FAILED: 'Tải tệp lên thất bại',
    AVATAR_UPLOAD_FAILED: 'Tải ảnh đại diện lên thất bại',
    AVATAR_DELETE_FAILED: 'Xóa ảnh đại diện thất bại',
    AVATAR_DELETED_SUCCESS: 'Xóa ảnh đại diện thành công',
    AVATAR_NOT_EXIST: 'Người dùng không có ảnh đại diện',
    PASSWORD_NOT_MATCH: 'Mật khẩu không khớp',
    EMAIL_NOT_CHANGED: 'Email không thay đổi',
    EMAIL_UPDATE_FAILED: 'Cập nhật email thất bại',
    CAN_NOT_CHANGE_ME: 'Bạn không thể áp dụng thao tác này cho chính mình',
    USER_DISABLED_CANNOT_CHAT:
        'Người dùng này đã vô hiệu hóa, không thể tiếp tục trò chuyện',
} as const;
