export const USER_MESSAGES = {
    EMAIL_EXISTED: 'Email already existed',
    NOT_AUTHORIZED_UPDATE: 'You are not authorized to update this user',
    USER_NOT_FOUND: 'User not found',
    USER_DISABLED: 'User has been disabled',
    USER_ALREADY_DISABLED: 'User is already disabled',
    USER_NOT_DISABLED: 'User is not disabled',
    DISABLE_SUCCESS: 'User disabled successfully',
    ENABLE_SUCCESS: 'User enabled successfully',
    CANNOT_DISABLE_ADMIN: 'Cannot disable an admin account',
    CANNOT_ENABLE_SELF: 'You cannot enable yourself from this endpoint',
    USER_ALREADY_ACTIVE: 'User is already active',
    ACTIVE_SUCCESS: 'Active user successfully',
    CODE_EXPIRED: 'Code has expired',
    INVALID_CODE: 'Invalid code',
    INVALID_PASSWORD: 'Invalid password',
    CHANGE_PASSWORD_SUCCESS: 'Change password successfully',
    EMAIL_NOT_FOUND: 'Email not found',
    RESET_PASSWORD_SUCCESS: 'Reset password successfully',
    PLEASE_WAIT_COOLDOWN: (waitTime: number) =>
        `Please wait ${waitTime} seconds before requesting a new code.`,
    FILE_UPLOAD_FAILED: 'File upload failed',
    AVATAR_UPLOAD_FAILED: 'Avatar upload failed',
    AVATAR_DELETE_FAILED: 'Avatar delete failed',
    AVATAR_DELETED_SUCCESS: 'Avatar deleted successfully',
    AVATAR_NOT_EXIST: 'User not have avatar',
} as const;
