export const RELATIONSHIP_MESSAGES = {
    RELATIONSHIP_NOT_FOUND: 'Không tìm thấy relationship',
    UPDATE_FAILED: 'Cập nhật relationship thất bại',
    FRIEND_REQUEST_ALREADY_SENT: 'Bạn đã gửi yêu cầu kết bạn trước đó',
    CREATE_FAILED: 'Tạo relationship thất bại',
    ALREADY_BLOCKED: 'Bạn đã chặn người này trước đó',
    CANNOT_BLOCK: 'Không thể chặn người này',
    BLOCK_FAILED: 'Chặn thất bại',
    UNBLOCK_FAILED: 'Bỏ chặn thất bại',
    ALREADY_ACCEPTED: 'Relationship has been accepted',
    RELATIONSHIP_ALREADY_BLOCKED: 'Relationship has been blocked',
    CANNOT_BE_SAME_USER: 'Không thể gửi yêu cầu kết bạn cho chính mình',
    USER_NOT_FOUND: 'Không tìm thấy người dùng',
    REQUESTER_NOT_ACTIVE: 'Tài khoản của bạn chưa kích hoạt',
    REQUESTER_DISABLED: 'Tài khoản của bạn đã bị vô hiệu hóa',
    RECIPIENT_NOT_ACTIVE: 'Tài khoản nhận yêu cầu chưa kích hoạt',
    RECIPIENT_DISABLED: 'Tài khoản nhận yêu cầu đã bị vô hiệu hóa',
} as const;
