export const VALIDATION_MESSAGES = {
    EMAIL_REQUIRED: 'Email không được để trống',
    EMAIL_INVALID: 'Email không đúng định dạng',
    EMAIL_OR_PHONE_REQUIRED: 'Email hoặc số điện thoại không được để trống',
    EMAIL_OR_PHONE_INVALID: 'Email hoặc Số điện thoại không hợp lệ',
    IDENTIFIER_REQUIRED: 'Email hoặc số điện thoại không được để trống',
    IDENTIFIER_INVALID: 'Email hoặc Số điện thoại không hợp lệ',
    PASSWORD_REQUIRED: 'Mật khẩu không được để trống',
    PASSWORD_MIN_LENGTH: 'Mật khẩu phải có ít nhất 6 ký tự',
    OLD_PASSWORD_REQUIRED: 'Mật khẩu cũ không được để trống',
    OLD_PASSWORD_MIN_LENGTH: 'Mật khẩu cũ phải có ít nhất 6 ký tự',
    NEW_PASSWORD_REQUIRED: 'Mật khẩu mới không được để trống',
    NEW_PASSWORD_MIN_LENGTH: 'Mật khẩu mới phải có ít nhất 6 ký tự',
    CONFIRM_PASSWORD_REQUIRED: 'Xác nhận mật khẩu không được để trống',
    CONFIRM_PASSWORD_MIN_LENGTH: 'Xác nhận mật khẩu phải có ít nhất 6 ký tự',
    CONFIRM_PASSWORD_NOT_MATCH: 'Xác nhận mật khẩu không khớp',
    CODE_REQUIRED: 'Mã không được để trống',
    CODE_INVALID: 'Mã không hợp lệ',
    VALIDATION_FAILED: 'Dữ liệu không hợp lệ',
    NAME_REQUIRED: 'Tên không được để trống',
    NAME_STRING: 'Tên phải là chuỗi',
    PHONE_INVALID: 'Số điện thoại không hợp lệ',
    ADDRESS_STRING: 'Địa chỉ phải là chuỗi',
    DATE_OF_BIRTH_INVALID: 'Ngày sinh không hợp lệ',
    DATE_OF_BIRTH_FUTURE: 'Ngày sinh không được ở tương lai',
    GENDER_INVALID: 'Giới tính không hợp lệ',
    BIO_STRING: 'Tiểu sử phải là chuỗi',
    ROLE_REQUIRED: 'Vai trò không được để trống',
    ROLE_INVALID: 'Vai trò phải là USER hoặc ADMIN',
    REASON_REQUIRED: 'Lý do không được để trống',
    REASON_STRING: 'Lý do phải là chuỗi',
    DESCRIPTION_REQUIRED_FOR_OTHER_REASON:
        'Mô tả là bắt buộc khi chọn lý do Khác',
    STATUS_REQUIRED: 'Trạng thái không được để trống',
    STATUS_INVALID: 'Trạng thái không hợp lệ',
    FILE_REQUIRED: 'Vui lòng tải lên tệp',
    MIN_ONE_MEMBER: 'Vui lòng chọn ít nhất một thành viên',
} as const;
