export const CONVERSATION_MESSAGES = {
    DIRECT_MUST_BE_2_USERS: 'Trò chuyện trực tiếp phải là 2 người',
    GROUP_NAME_REQUIRED: 'Vui lòng nhập tên nhóm',
    GROUP_MIN_3_USERS: 'Trò chuyện nhóm phải có ít nhất 3 người',
    USERS_NOT_EXIST: 'Một hoặc nhiều người dùng không tồn tại',
    USER_NOT_FOUND: 'Không tìm thấy người dùng',
    NAME_REQUIRED: 'Vui lòng nhập tên',
    CANNOT_REMOVE_ADMIN: 'Không thể xóa quản trị viên của nhóm này',
    NOT_A_MEMBER: 'Người dùng không thuộc cuộc trò chuyện',
    USER_DISABLED:
        'Người dùng này vô hiệu hóa tài khoản, không thể tiếp tục trò chuyện',
    ALREADY_HIDDEN: 'Cuộc trò chuyện đã bị ẩn',
    DELETE_SUCCESS: 'Xóa cuộc trò chuyện thành công',
    DELETE_FAILED: 'Không thể xóa cuộc trò chuyện',
    CANNOT_READ_OLDER: 'Không thể đánh dấu đã đọc cho tin nhắn cũ hơn',
    MESSAGE_NOT_FOUND: 'Không tìm thấy tin nhắn',
    CONVERSATION_NOT_FOUND: 'Không tìm thấy cuộc trò chuyện',
    USER_NOT_ACCEPTED_CONVERSATION: 'Người dùng chưa chấp nhận cuộc trò chuyện',
    DIRECT_ACTION_NOT_ALLOWED:
        'Không thể thực hiện thao tác này với cuộc trò chuyện trực tiếp',
    NOT_GROUP_ADMIN: 'Bạn không phải là quản trị viên của nhóm này',
    USER_NOT_IN_CONVERSATION: 'Người dùng không có trong cuộc trò chuyện',
    MEMBER_REQUIRED: 'Vui lòng chọn thành viên cần xóa',
    NAME_NOT_CHANGED: 'Tên không thay đổi',
    CURRENT_USER_IS_ALREADY_ADMIN: 'Người dùng hiện tại đã là quản trị viên',
    NOT_A_GROUP: 'Đây không phải là cuộc trò chuyện nhóm',
    AVATAR_UPLOAD_FAILED: 'Tải ảnh đại diện lên thất bại',
    AVATAR_NOT_FOUND: 'Không tìm thấy ảnh đại diện',
    AVATAR_DELETE_FAILED: 'Xóa ảnh đại diện thất bại',
    AVATAR_NOT_EXIST: 'Chưa có ảnh đại diện',
    CANNOT_BLOCK_IN_GROUP:
        'Không thể chặn người dùng trong cuộc trò chuyện nhóm',
    ALREADY_ACCEPTED: 'Bạn đã chấp nhận cuộc trò chuyện này rồi',
    ACCEPT_SUCCESS: 'Chấp nhận cuộc trò chuyện thành công',
    DISABLED_ACCOUNT_NAME: 'Tài khoản vô hiệu hóa',
    ADMIN_LABEL: 'Quản trị viên',
    MEMBER_LABEL: 'một thành viên',
    SYSTEM_ADDED_MEMBERS: (names: string) =>
        `Quản trị viên đã thêm ${names} vào nhóm`,
    SYSTEM_LEFT_GROUP: (name: string) => `${name} đã rời khỏi nhóm`,
    SYSTEM_REMOVED_FROM_GROUP: (name: string) =>
        `Quản trị viên đã xóa ${name} khỏi nhóm`,
    SYSTEM_TRANSFER_ADMIN: (currentName: string, newName: string) =>
        `${currentName} đã chuyển quyền quản trị viên cho ${newName}`,
} as const;
