export const MEDIA_CONSTANTS = {
    MAX_IMAGE_FILE_SIZE: 10 * 1024 * 1024,
    USER_AVATAR_FOLDER: 'users/avatars',
    CONVERSATION_AVATAR_FOLDER: 'conversations/avatars',
    CONVERSATION_IMAGE_FOLDER: 'conversations/images',
    CONVERSATION_VIDEO_FOLDER: 'conversations/videos',
    CONVERSATION_AUDIO_FOLDER: 'conversations/audio',
    CONVERSATION_FILE_FOLDER: 'conversations/files',
    REPORT_EVIDENCE_FOLDER: 'reports/evidence',
    SIGNED_URL_TTL_SECONDS: 60,
} as const;

export const MEDIA_MESSAGES = {
    OWNER_TYPE_NOT_SUPPORT: 'Không hỗ trợ loại tệp này',
    FILE_UPLOAD_OVER_LIMIT: 'Đã vượt quá số lượng tệp cho phép',
    FILE_UPLOAD_EMPTY: 'Vui lòng tải lên ít nhất một tệp',
    FILE_UPLOAD_FAILED: 'Tải tệp lên thất bại',
    FILE_IS_TOO_LARGE: 'Tệp quá lớn',
    WRONG_FILE_TYPE: 'Loại tệp không hợp lệ',
    FILE_NOT_FOUND: 'Không tìm thấy tệp',
    MEDIA_CREATE_FAILED: 'Tạo media thất bại',
    MEDIA_NOT_FOUND: 'Không tìm thấy media',
    MEDIA_ACCESS_DENIED: 'Bạn không có quyền truy cập media này',
    MEDIA_CONTENT_NOT_FOUND: 'Không tìm thấy nội dung media',
    MEDIA_NOT_STORED_IN_R2: 'Media không được lưu trong R2',
    MEDIA_DELETE_FAILED: 'Xóa media thất bại',
    PUBLIC_ID_NOT_FOUND: 'Không tìm thấy public ID',
    AVATAR_DELETE_FAILED: 'Xóa ảnh đại diện thất bại',
    OBJECT_KEY_NOT_FOUND: 'Không tìm thấy object key',
    R2_CONFIGURATION_MISSING: 'Thiếu cấu hình R2',
    R2_BUCKET_NAME_MISSING: 'Thiếu tên bucket R2',
    CLOUDINARY_UPLOAD_FAILED: 'Tải tệp lên Cloudinary thất bại',
    MEDIA_URL_UNAVAILABLE: 'Không thể tạo liên kết cho media này',
} as const;
